Ajustes para versão web

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -22,10 +22,10 @@ jobs:
         run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
-      - name: fetch CNAME from web branch
+      - name: fetch CNAME from dist branch
         run: |
-          git fetch origin web:web || echo "Branch web não encontrada, pulando..."
-          git show web:CNAME > CNAME || echo "CNAME not found, skipping"
+          git fetch origin dist:dist || echo "Branch dist não encontrada, pulando..."
+          git show dist:CNAME > CNAME || echo "CNAME not found, skipping"
       - name: install dependencies
         run: npm ci --ignore-scripts
       - name: build project
@@ -41,12 +41,12 @@ jobs:
       - name: copy index.html to 404.html
         run: |
           cp dist/index.html dist/404.html
-      - name: deploy to web
+      - name: deploy to dist
         run: |
           cd dist
           git init
-          git checkout -b web  # Cria a branch web se não existir
+          git checkout -b dist  # Cria a branch dist se não existir
           git add -A
           git commit -m "🚀 Deploy id ${GITHUB_RUN_ID}"
           git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
-          git push -f origin web  # Faz push forçado para a branch web
+          git push -f origin dist  # Faz push forçado para a branch dist
